[tool.black]
line-length = 99
skip-numeric-underscore-normalization = 1
exclude = ''

[tool.isort]
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
known_third_party = ""
known_first_party = "dailyconsumption,dashboard,data,domain"
default_section = "THIRDPARTY"
use_parentheses = "True"
line_length = 99
skip_glob=""
